### ISSUE TITLE
Correctly escape URLs.

### ISSUE THREAD

**Issue by PurpleMyst** [Juulsn/todo-issue#10]
As per the title, the bot does not currently correctly handle spaces in filenames and/or folder names. I am unable to demonstrate this as I encountered the bug in a private repository.

I would be willing to lend a hand in fixing this given guidance on where to look in the codebase.

Thank you in advance.

**Comment by DerJuulsn** [comment]
I don't really get what you mean.

Could you send me the line which you are trying to parse?
Furthermore, the result you get and an example of how it should look like.

If I had to guess, I think you are trying to add some kind of uri and want GitHub to make a hyperlink out of it?

**Comment by Juulsn** [comment]
Hey, I've looked into it but couldn't reproduce it.
Could you give me some more details about this?

If I understand you correctly, you have some file named 'Sample File.txt' and the bot doesn't find this one?
Does this just not work for the import all option or in general?

**Comment by PurpleMyst** [comment]
Given a file in a folder that has spaces (e.g. `MY FOLDER NAME/FILE`), you'll get something of the form:
`https://github.com/PurpleMyst/REPO/blob/HASH/MY FOLDER NAME/FILE#L796-L801`
which "ends" at the word "MY" and the part beginning with "FOLDER" is not counted as part of the URL, while it should be.

**Comment by Juulsn** [comment]
Okay, got you. So its just the link in the bot's comment which isn't correct, but the issue still gets generated. I'll look into it.

**Comment by PurpleMyst** [comment]
Thank you very much. Is there any way to fix existing issues now?

**Comment by Juulsn** [comment]
Hm, you could delete (yes delete, not close) the old issue and use the import all function, which only imports issues not created yet. That's why you have to delete the original issue.

**Comment by PurpleMyst** [comment]
Understandable. Thank you again.
