### ISSUE TITLE
Chinese annotation title acquisition problem

### ISSUE THREAD

**Issue by eryajf** [Juulsn/todo-issue#14]
When the annotation is in Chinese, the title of the issue only takes the last word.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/33259379/175048149-05a246a2-8368-4fa8-b56e-6b2ea4fe814c.png">

**Comment by Juulsn** [comment]
Fixed with commit [4135985](https://github.com/DerJuulsn/todo-issue/commit/4135985ede9c6637c342b8fa881a4f59a7aad947)
